#!/bin/bash -e

echo usage restoremysql MYSQL_DATABASE otherparams 
MYSQL_DATABASE=$1
shift

echo "Restoring database ${MYSQL_DATABASE}"

restore --file-to-restore volumerize-mysql/dump-${MYSQL_DATABASE}.sql $@

source /postexecute/mysqlimport.sh