#!/bin/bash

set -o errexit

[[ ${DEBUG} == true ]] && set -x

source /opt/volumerize/base.sh

export VOLUMERIZE_COMMAND="backupFull"
DUPLICITY_RETURN_CODE=0

if [ ! -z "${1##*[!0-9]*}" ]; then
  export JOB_ID=$1
  shift
fi

function commandJob() {
  local returnCode=0;
  if [ -z "$JOB_ID" ]; then
    eval ${DUPLICITY_COMMAND} full "$@" ${DUPLICITY_OPTIONS} ${VOLUMERIZE_INCLUDES} ${VOLUMERIZE_EXCLUDES} ${VOLUMERIZE_SOURCE} ${VOLUMERIZE_TARGET} || returnCode=$? && true ;
  else
    prepareJob "$JOB_ID"
    eval ${DUPLICITY_JOB_COMMAND} full "$@" ${DUPLICITY_JOB_OPTIONS} ${VOLUMERIZE_JOB_INCLUDES} ${VOLUMERIZE_JOB_EXCLUDES} ${VOLUMERIZE_JOB_SOURCE} ${VOLUMERIZE_JOB_TARGET} || =$? && true ;
  fi
  if [ "$returnCode" -gt "$DUPLICITY_RETURN_CODE" ]; then
    DUPLICITY_RETURN_CODE=$returnCode
  fi
}

${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy preAction backup
${VOLUMERIZE_SCRIPT_DIR}/stopContainers.sh
commandExecution "$@"
${VOLUMERIZE_SCRIPT_DIR}/startContainers.sh
export DUPLICITY_RETURN_CODE
${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy postAction backup
exit $DUPLICITY_RETURN_CODE
