#!/bin/bash

set -o errexit

[[ ${DEBUG} == true ]] && set -x

source /opt/volumerize/base.sh
source /opt/volumerize/find_job_id.sh

export VOLUMERIZE_COMMAND="cleanup"
DUPLICITY_RETURN_CODE=0

function commandJob() {
  local returnCode=0;
  eval ${DUPLICITY_JOB_COMMAND} cleanup "$@" ${DUPLICITY_JOB_OPTIONS} ${VOLUMERIZE_JOB_INCLUDES} ${VOLUMERIZE_JOB_EXCLUDES} ${VOLUMERIZE_JOB_TARGET} || returnCode=$? && true ;
  if [ "$returnCode" -gt "$DUPLICITY_RETURN_CODE" ]; then
    DUPLICITY_RETURN_CODE=$returnCode
  fi
}

commandExecution "$@"
exit $DUPLICITY_RETURN_CODE
