#!/bin/bash

set -o errexit

[[ ${DEBUG} == true ]] && set -x

source /opt/volumerize/base.sh

export VOLUMERIZE_COMMAND="remove-all-inc-of-but-n-full"
DUPLICITY_RETURN_CODE=0

if [ ! -z "${1##*[!0-9]*}" ] && [ ! -z "${2##*[!0-9]*}" ]; then
  export JOB_ID=$1
  shift
fi

function commandJob() {
  local returnCode=0;
  eval ${DUPLICITY_JOB_COMMAND} remove-all-inc-of-but-n-full "$@" ${DUPLICITY_JOB_OPTIONS} ${VOLUMERIZE_JOB_TARGET} || returnCode=$? && true ;
  if [ "$returnCode" -gt "$DUPLICITY_RETURN_CODE" ]; then
    DUPLICITY_RETURN_CODE=$returnCode
  fi
}

${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy preAction remove
commandExecution "$@"
${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy postAction remove
exit $DUPLICITY_RETURN_CODE
