#!/bin/bash

set -o errexit

[[ ${DEBUG} == true ]] && set -x

source /opt/volumerize/base.sh

DUPLICITY_RETURN_CODE=0

function commandLoop() {
  local jobcount=$JOB_COUNT
  local counter;

  for (( counter=1; counter<=$jobcount; counter++ ))
  do
    commandJob "$counter" $@
  done
}

function commandJob() {
  local jobNumber=$1
  local returnCode=0;
  prepareJob "$jobNumber"
  shift;
  ${DUPLICITY_JOB_COMMAND} verify --compare-data $@ ${DUPLICITY_JOB_OPTIONS} ${VOLUMERIZE_JOB_INCUDES} ${VOLUMERIZE_JOB_TARGET} ${VOLUMERIZE_JOB_RESTORE} || returnCode=$? && true ;
  if [ "$returnCode" -gt "$DUPLICITY_RETURN_CODE" ]; then
    DUPLICITY_RETURN_CODE=$returnCode
  fi
}

function commandExecution() {
  if [ -n "${VOLUMERIZE_SOURCE}" ]; then
	args=$@
    while true; do
		case "$1" in
			"" )break;;
			--file-to-restore )
				file_to_restore="$2";
				shift ;;
			*) shift;;
		  esac
		done
	if [ -z "$file_to_restore" ];then
			echo "--file-to-restore argument is not set"
			exit 10
	fi
    ${DUPLICITY_COMMAND} restore --force $args ${DUPLICITY_OPTIONS} ${VOLUMERIZE_INCUDES} ${VOLUMERIZE_TARGET} "${VOLUMERIZE_RESTORE}/$file_to_restore" || DUPLICITY_RETURN_CODE=$? && true ;
  elif [ ! -z "${1##*[!0-9]*}" ]; then
    commandJob $@
  elif [ -n "${JOB_COUNT}" ]; then
    commandLoop $@
  fi
}

${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy preAction verify
commandExecution $@
${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy postAction verify
exit $DUPLICITY_RETURN_CODE
