name: Bump version
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
    paths:
      - 'imagescripts/**'
      - 'postexecute/**'
      - 'prepost_strategies/**'
      - 'scripts'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bump
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.TAGGING_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.0.0
    - name: Create release
      uses: ncipollo/release-action@v1.16.0
      with:
        tag:  ${{ steps.bump.outputs.new_tag }}
